version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend
    command: /bin/run.sh
    depends_on:
      - redis
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "5002:5002"
    volumes:
      - .:/opt/copr:z

  redis:
    image: centos/redis-32-centos7
    hostname: redis

  builder:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    hostname: builder
    command: /bin/run.sh
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - .:/opt/copr:z

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    hostname: frontend
    command: /bin/run.sh
    depends_on:
      - database
      - redis
    links:
      - database
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/copr:z

  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    hostname: database
    command: /bin/run.sh
    stdin_open: true
    tty: true
    ports:
      - 5432:5432

  distgit:
    build:
      context: .
      dockerfile: docker/distgit/Dockerfile
    hostname: distgit
    command: /bin/run.sh
    stdin_open: true
    tty: true
    ports:
      - "5001:80"
    volumes:
      - .:/opt/copr:z
