version: '3'
services:

  # @TODO Probably not all backend services should use the same Dockerfile

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend
    command: /usr/sbin/runuser -u copr -g copr -- /usr/bin/copr_be.py
    depends_on:
      - backend-log
      - backend-vmm
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - results:/var/lib/copr/public_html/results
      - backend-etc:/etc

  backend-log:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend-log
    command: /usr/sbin/runuser -u copr -g copr -- /usr/bin/copr_run_logger.py
    depends_on:
      - redis
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - results:/var/lib/copr/public_html/results
      - backend-etc:/etc

  backend-vmm:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend-vmm
    command: /usr/sbin/runuser -u copr -g copr -- /usr/bin/copr_run_vmm.py
    depends_on:
      - backend-log
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - results:/var/lib/copr/public_html/results
      - backend-etc:/etc

  backend-build:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend-build
    command: /usr/sbin/runuser -u copr -g copr -G obsrun -- /usr/bin/copr_run_build_dispatcher.py
    depends_on:
      - backend-log
      - backend-vmm
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - results:/var/lib/copr/public_html/results
      - backend-etc:/etc

  backend-action:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend-action
    command: /usr/sbin/runuser -u copr -g copr -- /usr/bin/copr_run_action_dispatcher.py
    depends_on:
      - backend-log
      - backend-vmm
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - results:/var/lib/copr/public_html/results
      - backend-etc:/etc

  backend-signd:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend-signd
    command: /usr/sbin/runuser -u copr -g copr -- /usr/sbin/signd
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - results:/var/lib/copr/public_html/results
      - backend-etc:/etc

  redis:
    image: centos/redis-32-centos7
    hostname: redis

  backend_httpd:
    build:
      context: .
      dockerfile: docker/backend_httpd/Dockerfile
    hostname: backend_httpd
    ports:
      - "5002:5002"
    volumes:
      - results:/var/lib/copr/public_html/results

  builder:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    hostname: builder
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - .:/opt/copr:z

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    hostname: frontend
    depends_on:
      - database
      - redis
    links:
      - database
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/copr:z

  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    hostname: database
    stdin_open: true
    tty: true
    environment:
      - POSTGRESQL_USER=copr-fe
      - POSTGRESQL_PASSWORD=coprpass
      - POSTGRESQL_DATABASE=coprdb
    ports:
      - 5432:5432

  distgit:
    build:
      context: .
      dockerfile: docker/distgit/Dockerfile
    hostname: distgit
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - dist-git:/var/lib/dist-git

  distgit-httpd:
    build:
      context: .
      dockerfile: docker/distgit-httpd/Dockerfile
    hostname: distgit-httpd
    stdin_open: true
    tty: true
    ports:
      - "5001:80"
    volumes:
      - .:/opt/copr:z
      - dist-git:/var/lib/dist-git

  keygen-signd:
    build:
      context: .
      dockerfile: docker/keygen-signd/Dockerfile
    hostname: keygen-signd
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - copr-keygen:/var/lib/copr-keygen

  keygen-httpd:
    build:
      context: .
      dockerfile: docker/keygen-httpd/Dockerfile
    hostname: keygen-httpd
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - copr-keygen:/var/lib/copr-keygen

volumes:
  results:
  copr-keygen:
  dist-git:
  backend-etc:
