version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend
    command: /bin/run.sh
    depends_on:
      - redis
      - backend_httpd
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - .:/opt/copr:z
      - results:/var/lib/copr/public_html/results

  redis:
    image: centos/redis-32-centos7
    hostname: redis

  backend_httpd:
    build:
      context: .
      dockerfile: docker/backend_httpd/Dockerfile
    hostname: backend_httpd
    ports:
      - "5002:5002"
    volumes:
      - results:/var/lib/copr/public_html/results

  builder:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    hostname: builder
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - .:/opt/copr:z

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    hostname: frontend
    depends_on:
      - database
      - redis
    links:
      - database
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/copr:z

  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    hostname: database
    command: /bin/run.sh
    stdin_open: true
    tty: true
    ports:
      - 5432:5432

  distgit:
    build:
      context: .
      dockerfile: docker/distgit/Dockerfile
    hostname: distgit
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - dist-git:/var/lib/dist-git

  distgit-httpd:
    build:
      context: .
      dockerfile: docker/distgit-httpd/Dockerfile
    hostname: distgit-httpd
    stdin_open: true
    tty: true
    ports:
      - "5001:80"
    volumes:
      - .:/opt/copr:z
      - dist-git:/var/lib/dist-git

  keygen-signd:
    build:
      context: .
      dockerfile: docker/keygen-signd/Dockerfile
    hostname: keygen-signd
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - copr-keygen:/var/lib/copr-keygen

  keygen-httpd:
    build:
      context: .
      dockerfile: docker/keygen-httpd/Dockerfile
    hostname: keygen-httpd
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/copr:z
      - copr-keygen:/var/lib/copr-keygen

volumes:
  results:
  copr-keygen:
  dist-git:
