---
- name: create instance
  hosts: localhost
  remote_user: root
  gather_facts: False
  tasks:
  - name: generate builder name
    local_action: command echo "Copr builder {{ 999999999 | random }}"
    register: vm_name

  - debug: msg="IP=127.0.0.1"
  - debug: msg="vm_name={{vm_name.stdout}}"
