---
- name: create instance
  hosts: builder
  remote_user: root
  gather_facts: True
  tasks:
  - name: generate builder name
    local_action: command echo "Copr builder {{ 999999999 | random }}"
    register: vm_name

  - name: register builder IP
    shell: getent hosts builder | awk '{ print $1 }'
    register: vm_ip

  - debug: msg="IP={{vm_ip.stdout}}"
  - debug: msg="vm_name={{vm_name.stdout}}"
