---
- name: check/create instance
  hosts: localhost
  user: root
  gather_facts: False

  tasks:
  - name: install pkgs
    action: yum state=present pkg={{ item }}
    with_items:
    - http://mirror.oss.ou.edu/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
    - mock
    - mock-lvm
    - yum-utils
    - rsync
    - openssh-clients

  - name: make sure newest rpm
    action: yum name=rpm state=latest

  # sometime we need, sometimes not. If you do not need it, just comment it out
  - yum: name=mock  enablerepo=epel-testing state=latest

  - name: mockbuilder user
    action: user name=mockbuilder groups=mock

  - name: mockbuilder .ssh
    action: file state=directory path=/home/mockbuilder/.ssh mode=0700 owner=mockbuilder group=mockbuilder

  - name: prepare caches
    action: command mock -r {{ item }} --init
    with_items:
    - epel-5-i386
    - epel-5-x86_64
    - epel-6-i386
    - epel-6-x86_64
    - epel-7-x86_64
    - fedora-20-i386
    - fedora-20-x86_64
    - fedora-21-i386
    - fedora-21-x86_64
    - fedora-rawhide-i386
    - fedora-rawhide-x86_64
