- name: install pkgs
  yum: state=present pkg={{ item }}
  with_items:
    - dnf
    - mock
    - mock-lvm
    - createrepo
    - yum-utils
    - pyliblzma
    - rsync
    - openssh-clients
    - rsync
    - libselinux-python
    - libsemanage-python

- name: make sure newest rpm
  yum: name={{ item }} state=latest
  with_items:
    - rpm
    - glib2
    - ca-certificates

- name: put updated mock configs into /etc/mock
  copy: src=files/{{ item }} dest=/etc/mock
  with_items:
    - site-defaults.cfg

- name: prepare caches
  async: 3600
  command: mock -r {{ item }} --init
  with_items:
    - epel-5-i386
    - epel-5-x86_64
    - epel-6-i386
    - epel-6-x86_64
    - epel-7-x86_64
    - fedora-20-i386
    - fedora-20-x86_64
    - fedora-21-i386
    - fedora-21-x86_64
    - fedora-22-i386
    - fedora-22-x86_64
    - fedora-rawhide-i386
    - fedora-rawhide-x86_64

- name: mockbuilder user
  user: name=mockbuilder groups=mock

- name: mockbuilder .ssh
  file: state=directory path=/home/mockbuilder/.ssh mode=0700 owner=mockbuilder group=mockbuilder

- name: mockbuilder authorized_keys
  authorized_key: user=mockbuilder key='{{ lookup('file', '/home/copr/provision/files/buildsys.pub') }}'

- name: root authorized_keys
  authorized_key: user=root key='{{ lookup('file', '/home/copr/provision/files/buildsys.pub') }}'

- lineinfile: dest=/etc/mock/fedora-rawhide-x86_64.cfg line="config_opts['package_manager'] = 'dnf'" state=absent
- lineinfile: dest=/etc/mock/fedora-rawhide-i386.cfg line="config_opts['package_manager'] = 'dnf'" state=absent

- lineinfile: dest=/etc/security/limits.conf line="* soft nofile 10240" insertafter=EOF
- lineinfile: dest=/etc/security/limits.conf line="* hard nofile 10240" insertafter=EOF
